

pipeline {
    agent any

    environment {
        TERRAGRUNT_DIR = "env/stage/infr"
        AWS_REGION = "eu-central-1"
    }

    stages {
        stage('Checkout Repository') {
            steps {
                echo "Checking out repository..."
                checkout scm
            }
        }

        stage('Validate Terragrunt') {
            steps {
                sh 'echo "Terragrunt version:"'
                sh 'terragrunt --version'
            }
        }

        stage('Terragrunt Init & Plan') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-stage-account'
                ]]) {
                    sh """
                        export AWS_DEFAULT_REGION=${AWS_REGION}
                        cd ${TERRAGRUNT_DIR}
                        terragrunt init
                        terragrunt plan
                    """
                }
            }
        }

        stage('Terragrunt Apply') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-stage-account'
                ]]) {
                    sh """
                        export AWS_DEFAULT_REGION=${AWS_REGION}
                        cd ${TERRAGRUNT_DIR}
                        terragrunt apply -auto-approve
                    """
                }
            }
        }
    }
}


